# ============================================================
# Holarchy Self-Healing System - Single Source of Truth (SSOT)
# ============================================================
# 이 파일 하나가 전체 시스템의 진실 소스입니다.
# 검증 실패 → 시스템 중단 (X)
# 검증 실패 → 문제 기록만 (O)
# ============================================================

project:
  name: "holarchy"
  version: "2.0"
  mode: "self-healing"  # 강제성 없음, 관찰/추천만

paths:
  docs_dir: "0 Docs/holons"
  reports_dir: "0 Docs/reports"
  decisions_dir: "0 Docs/decisions"
  meetings_dir: "0 Docs/meetings"
  legacy_dir: "0 Docs/_legacy"

# ============================================================
# 레이어 구조 정의
# ============================================================
layers:
  - id: "layer-0"
    name: "0 Docs"
    purpose: "문서 및 지식 저장소"
    subdirs:
      - holons      # 핵심 Holon 문서
      - decisions   # 의사결정 기록
      - meetings    # 회의록
      - reports     # 자동 생성 보고서

  - id: "layer-1"
    name: "1 Astral"
    purpose: "상위 추상화 레이어 (정보체/지식체/실행체)"
    subdirs:
      - .holon      # 엔진 코드
      - "1 정보체"   # 정보 수집/처리
      - "2 지식체"   # 지식 구조화
      - "3 실행체"   # 실행/액션

  - id: "layer-2"
    name: "2 Neural"
    purpose: "신경망 처리 레이어 (인덱싱/쿼리)"
    subdirs:
      - index       # 인덱스 빌드
      - resolver    # 좌표 파싱
      - activation  # 활성화 로직
      - api         # API 엔드포인트
      - ui          # 네비게이터 UI

# ============================================================
# 문서 정의
# ============================================================
documents:
  # Root 문서 (헌법)
  - id: "hte-doc-000"
    file: "00-holarchy-overview.md"
    type: "strategy"
    title: "Holarchy Overview - 전체 시스템 헌법"
    is_root: true

  # 조직/전략 문서
  - id: "hte-doc-001"
    file: "01-organizational-structure.md"
    type: "structure"
    title: "조직 구조"
    parent: "hte-doc-000"

  - id: "hte-doc-002"
    file: "02-product-architecture.md"
    type: "structure"
    title: "제품 아키텍처"
    parent: "hte-doc-000"

  - id: "hte-doc-003"
    file: "03-operations-strategy.md"
    type: "strategy"
    title: "운영 전략"
    parent: "hte-doc-000"

  - id: "hte-doc-004"
    file: "04-investment-structure.md"
    type: "structure"
    title: "투자 구조"
    parent: "hte-doc-000"

  - id: "hte-doc-005"
    file: "05-api-system.md"
    type: "structure"
    title: "API 시스템"
    parent: "hte-doc-002"

  # 프레임워크
  - id: "hte-framework-001"
    file: "wxsperta-framework.md"
    type: "structure"
    title: "WXSPERTA Framework"
    parent: "hte-doc-000"

  # PM 전략
  - id: "strategy-2025-001"
    file: "strategy-2025-001-pm-system.md"
    type: "strategy"
    title: "AI PM 시스템"
    parent: "hte-doc-000"

  # Feature 문서
  - id: "feature-2025-001"
    file: "feature-2025-001-학생-진단-리포트.md"
    type: "feature"
    title: "학생 진단 리포트"
    parent: "strategy-2025-001"

  - id: "feature-2025-002"
    file: "feature-2025-002-시선-추적-ai-분석.md"
    type: "feature"
    title: "시선 추적 AI 분석"
    parent: "strategy-2025-001"

# ============================================================
# 의사결정 문서 (decisions 폴더)
# ============================================================
decisions:
  - id: "decision-2025-001"
    file: "decision-2025-001.md"
    type: "decision"
    title: "의사결정 001"
    parent: "hte-doc-000"

  - id: "decision-2025-003"
    file: "decision-2025-003.md"
    type: "decision"
    title: "의사결정 003"
    parent: "hte-doc-000"

  - id: "decision-2025-005"
    file: "decision-2025-005.md"
    type: "decision"
    title: "의사결정 005"
    parent: "hte-doc-000"

# ============================================================
# 회의록 문서 (meetings 폴더)
# ============================================================
meetings:
  - id: "meeting-2025-001"
    file: "meeting-2025-001-mvp-기능-범위-회의.md"
    type: "meeting"
    title: "MVP 기능 범위 회의"

  - id: "meeting-2025-002"
    file: "meeting-2025-002-ai-튜터-킥오프-회의.md"
    type: "meeting"
    title: "AI 튜터 킥오프 회의"

  # 참고: meeting-2025-003 ~ 015는 중복 제목으로 정리 필요
  # 현재 "질문하기-수정-해야-하는-오류,-문제점" 제목이 반복됨

# ============================================================
# 검증 규칙 - Self-Healing 모드
# ============================================================
rules:
  # 규칙 위반 시 severity에 따라 처리
  # error: 심각 (기록 + 빨간 경고)
  # warning: 주의 (기록 + 노란 경고)
  # info: 참고 (기록만)
  
  - id: "wxsperta_w_structure"
    description: "W 섹션에 worldview/will/intention/goal/activation 포함"
    severity: "warning"
    
  - id: "wxsperta_will_field"
    description: "모든 WXSPERTA 슬롯에 will 필드 존재"
    severity: "info"
    
  - id: "bidirectional_links"
    description: "parent-child 양방향 링크 일치"
    severity: "warning"
    
  - id: "no_orphan"
    description: "Root 외 모든 문서는 parent 필요"
    severity: "info"
    
  - id: "no_placeholder"
    description: "[...], TBD, TODO 등 플레이스홀더 없음"
    severity: "info"
    
  - id: "holon_id_format"
    description: "holon_id 형식 일관성"
    severity: "warning"

# ============================================================
# Self-Healing 설정
# ============================================================
healing:
  auto_record: true
  
  # 문제 발생 시 처리 방식
  on_error: "record"      # record | ignore | ask
  on_warning: "record"
  on_info: "record"
  
  # 보고서 자동 생성
  generate_reports: true
  
  # 점수 계산 방식 (참고용, 강제 아님)
  scoring:
    error_weight: 10
    warning_weight: 3
    info_weight: 1

# ============================================================
# CLI 명령 정의
# ============================================================
commands:
  check:
    description: "문서 검사 (기록만, 실패 없음)"
    output: "reports/issues.json"
    
  risk:
    description: "위험도 점수 계산"
    output: "reports/risk_score.json"
    
  suggest:
    description: "자동 수정 추천 생성"
    output: "reports/suggestions.json"
    
  report:
    description: "현재 이슈 리포트 보기"
    source: "reports/issues.json"

